version: '3.8'

services:
  temp-monitor:
    image: ubuntu:22.04
    container_name: temp-monitor-fan-control
    privileged: true
    network_mode: host
    volumes:
      - ./app:/app
      - /sys:/sys:ro
      - ./docker.run:/docker.run
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=admin
      - IPMI_ADDRESS=localhost
      - IPMI_USERNAME=ipmi_user
      - IPMI_PASSWORD=ipmi_password
      - DEBIAN_FRONTEND=noninteractive
    entrypoint: ["/bin/bash", "/docker.run"]
    ports:
      - "8443:8443"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8443/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=temp-monitor-fan-control"

networks:
  default:
    name: temp-monitor-network
    external: true
