version: '3.8'

services:
  ipmi-nvidia-fan-manager:
    build: 
      context: https://github.com/hrtsv/Ipmi-nVidiaGPU-FanManager.git
      dockerfile: Dockerfile
    container_name: ipmi-nvidia-fan-manager
    privileged: true
    network_mode: host
    volumes:
      - /sys:/sys:ro
      - /usr/bin/ipmitool:/usr/bin/ipmitool:ro
    environment:
      - IPMI_ADDRESS=localhost
      - IPMI_USERNAME=ipmi_user
      - IPMI_PASSWORD=ipmi_password
    ports:
      - "8443:8443"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      sh -c "
      echo 'Container IP addresses:' &&
      ip addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{print \$2}' | cut -d/ -f1 &&
      echo 'Starting application...' &&
      exec python /app/app.py"  # Adjust this to the actual command to start your application