services:
  temp-monitor:
    image: ubuntu:20.04
    container_name: temp-monitor-fan-control
    privileged: true
    network_mode: host
    volumes:
      - ./app:/app
      - /sys:/sys:ro
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=admin
      - IPMI_ADDRESS=localhost
      - IPMI_USERNAME=ipmi_user
      - IPMI_PASSWORD=ipmi_password
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y software-properties-common curl python3 python3-pip ipmitool openssl git &&
      add-apt-repository ppa:graphics-drivers/ppa &&
      curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add - &&
      curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list &&
      apt-get update &&
      apt-get install -y nvidia-container-toolkit-base &&
      pip3 install flask flask-restx pyjwt nvidia-ml-py3 &&
      if [ ! -f cert.pem ] || [ ! -f key.pem ]; then
        openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365 -subj '/CN=localhost'
      fi &&
      if [ ! -d Ipmi-nVidiaGPU-FanManager ]; then
        git clone https://github.com/hrtsv/Ipmi-nVidiaGPU-FanManager.git
      fi &&
      cp Ipmi-nVidiaGPU-FanManager/app/app.py . &&
      cp Ipmi-nVidiaGPU-FanManager/app/index.html . &&
      python3 app.py
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped