version: '3.8'

services:
  temp-monitor:
    image: ubuntu:22.04
    container_name: temp-monitor-fan-control
    privileged: true
    network_mode: host
    volumes:
      - ./app:/app
      - /sys:/sys:ro
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=admin
      - IPMI_ADDRESS=localhost
      - IPMI_USERNAME=ipmi_user
      - IPMI_PASSWORD=ipmi_password
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c '
      apt-get update &&
      apt-get install -y --no-install-recommends python3 python3-pip python3-venv openssl ipmitool curl &&
      useradd -m appuser &&
      chown -R appuser:appuser /app &&
      su appuser -c "python3 -m venv /app/venv &&
      . /app/venv/bin/activate &&
      pip install flask flask-restx pyjwt nvidia-ml-py3 tenacity &&
      if [ ! -f /app/cert.pem ] || [ ! -f /app/key.pem ]; then
        openssl req -x509 -newkey rsa:4096 -nodes -out /app/cert.pem -keyout /app/key.pem -days 365 -subj \"/CN=localhost\";
      fi &&
      python3 /app/app.py"
      '
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8443/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=temp-monitor-fan-control"

networks:
  default:
    name: temp-monitor-network
    external: true
