version: '3.8'

services:
  app:
    image: hrtsv/ipmi-nvidiagpu-fanmanager:latest
    build:
      context: https://github.com/hrtsv/Ipmi-nVidiaGPU-FanManager.git
    ports:
      - "5000:5000"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - .:/app
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y --no-install-recommends python3 python3-pip openssl ipmitool software-properties-common curl &&
      add-apt-repository ppa:graphics-drivers/ppa &&
      curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | apt-key add - &&
      curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list | tee /etc/apt/sources.list.d/nvidia-docker.list &&
      apt-get update &&
      apt-get install -y nvidia-container-toolkit-base &&
      pip3 install flask flask-restx pyjwt nvidia-ml-py3 tenacity &&
      if [ ! -f /app/cert.pem ] || [ ! -f /app/key.pem ]; then
        openssl req -x509 -newkey rsa:4096 -nodes -out /app/cert.pem -keyout /app/key.pem -days 365 -subj '/CN=localhost';
      fi &&
      python3 /app/app.py
      "
