version: '3.8'

services:
  ipmi-gpu-monitor:
    build:
      context: https://github.com/hrtsv/Ipmi-nVidiaGPU-FanManager.git
      dockerfile: Dockerfile
    container_name: ipmi-gpu-monitor
    privileged: true
    network_mode: host
    environment:
      - SECRET_KEY=mysecretkey
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=admin
      - IPMI_ADDRESS=your_ipmi_address
      - IPMI_USERNAME=your_ipmi_username
      - IPMI_PASSWORD=your_ipmi_password
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/host
    volumes:
      - /sys:/sys:ro
      - /usr/bin:/usr/local/bin/host:ro
      - temperature_logs:/temperature_logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    command: python /app/app.py

volumes:
  temperature_logs: